import mongoose from "mongoose";

/*
mongoose.Schema.Types.ObjectId - mongoose.Schema.Types.ObjectId is a special type in Mongoose that is used to define references between different documents in MongoDB. It represents a unique identifier for documents. This is auto generated by mongoDB and acts like a forigen key.
*/

const cartItemSchema = mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  productId: {
    type: String,
    required: true,
  },
  name: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  imageUrl: {
    type: String,
    required: true,
  },
  categories: {
    type: [String],
    required: true,
  },
  discounted: {
    type: Boolean,
    required: true,
    default: false,
  },
  price: {
    type: Number,
    required: true,
  },
});

const CartItems = mongoose.model("CartItem", cartItemSchema);
export default CartItems;
